version: "3.3"

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - dockercompose
  
  backend:
    depends_on: 
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes: 
      - "C://workspace//docker//5_COMPOSE//6_bind_mount//flask:/app"
    networks:
      - dockercompose

networks:
  dockercompose:
